
var general_type_layout = {
  element_id : 'general_info_panel',
  tab_name : 'General',
  properties : [
    { label : 'Title', property_uri : 'dc.title' },
    { label : 'Description', property_uri : 'dc.description' }
  ]
}


function makeSIMEditor(editor_id) {
  // Get hold of the element
  root_element = $( editor_id )
  // Make the root element into a tabs control
  var tab_control = root_element.tabs();

  var general_info_panel = buildFormPanel(general_type_layout, root_element)

  // Add the generic details tab
  // Working from http://jqueryui.com/demos/tabs/#...immediately_select_a_just_added_tab
  // and http://blog.favrik.com/2009/08/11/dynamically-adding-jquery-tabs-round2/
  tab_control.tabs('add','#'+general_type_layout.element_id,general_type_layout.tab_name);

  //tab_control.tabs('add','#default',"Default Properties");
  //tab_control.tabs('add','#t1',"Default Properties1");
  //tab_control.tabs('add','#t2',"Default Properties2");
  //tab_control.tabs('add','#t3',"Default Properties3");
}


// Paint the template for the General Tab
function buildFormPanel(layout_definition, parent_element) {
  // the class here is copied from the page generated by a static tab. It may change with versions of JQuery I guess, so beware!
  var p = parent_element.append("<div id=\""+layout_definition.element_id+"\" class=\"ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide\"></div>");
  var ul = p.append("<ul></ul>");
  var parent_context = "";

  var i=0;

  for ( p in layout_definition.properties ) {

    var propdef = layout_definition.properties[p]

    // Work out the root of the property name (The path to an array of values)
    var base_property_path = parent_context+propdef.property_uri

    // For each property, see if there is a value in the model, if so, output an appropriate control
    // For(blah...)

    // Finally, output an empty control to act as a "Next" value (If permitted by cardinality rules)
    var c = ul.append("<li><label for=\""+base_property_path+"["+i+"]\">"+propdef.label+"</label><input id=\""+base_property_path+"["+i+"]\" type=\"text\"/></li>")
  }

  // var data = $('<div id="'+tab_id+'"></div>').append(tab_content);
  // this.tabs.append(data).tabs('add', '#' + tab_id, tab_name);
  // this.tabs.tabs('select', '#' + tab_id);


}
