

/* -> A model is an object instance with some links to view data
 *   model :
 *      __metamodel
 *      property:1
 *      property:2
 *      property:3
 *      property:n
 *
 *  A property can be scalar or a collection
 *  Scalar properties can be values (int,str,...) or reference
 *  Reference properties can be expanded as needed, with their related data hanging off the graph tree
 *  all properties have the ability to store a graph URI - Not used for relational backends
 */
var the_model = {

  // Information about the model
  __metamodel : {},

  // A counter for producing blank nodes
  __blank_node_counter : 0,

  // The URI of the root node in the graph.. Essentially, the node we are editing
  __root_graph_uri : "",

  // Contains all the graphs related to this model
  __graphmap : {}
}

var general_type_layout = {
  element_id : 'general_info_panel',
  tab_name : 'General',
  properties : [
    { label : 'Title', property_uri : 'dc.title', cardinality:'m' },
    { label : 'Description', property_uri : 'dc.description' , cardinality:'1'}
  ]
}


function newBlankNode() {
  return "_b"+(the_model.__blank_node_counter++);
}

// Turn the div identified by editor_id into a semantic editing form
// This function is to be used for the creation of new descriptions rather than editing existing ones
function makeSIMEditor(editor_id) {
  // Get hold of the element
  root_element = $( editor_id )

  // Make the root element into a tabs control
  var tab_control = root_element.tabs();

  // For now, we are going to assume we are creating a new record
  the_model.__root_graph_uri = newBlankNode();
  the_model.__graphmap[the_model.__root_graph_uri] = {};

  var general_info_panel = buildFormPanel(general_type_layout, root_element, the_model.__root_graph_uri)

  // Add the generic details tab
  // Working from http://jqueryui.com/demos/tabs/#...immediately_select_a_just_added_tab
  // and http://blog.favrik.com/2009/08/11/dynamically-adding-jquery-tabs-round2/
  tab_control.tabs('add','#'+general_type_layout.element_id,general_type_layout.tab_name);

  //tab_control.tabs('add','#default',"Default Properties");
  //tab_control.tabs('add','#t1',"Default Properties1");
  //tab_control.tabs('add','#t2',"Default Properties2");
  //tab_control.tabs('add','#t3',"Default Properties3");
}


// Paint the template for the General Tab
function buildFormPanel(layout_definition, parent_element, root_object_uri) {

  // the class here is copied from the page generated by a static tab. It may change with versions of JQuery I guess, so beware!
  var p = parent_element.append("<div id=\""+layout_definition.element_id+"\" class=\"ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide\"></div>");
  var new_table = $(document.createElement('table'));

  p.append(new_table);

  var parent_context = "";

  var i=0;

  for ( p in layout_definition.properties ) {

    // The definition of this property within the layout for this panel
    var propdef = layout_definition.properties[p];

    // The path to the property -in the model-. Initially, depth of 1, this is the property uri
    // Later on, ns:prop[4].ns:subprop  (subprop within the 4th instance of prop)
    var property = propdef.property_uri;

    // Make sure we have an object for this property in the model
    var root_object = the_model.__graphmap[root_object_uri];
    var property_model = root_object[property];

    // If this is the first time we have seen this property, create a new empty metamodel (Will contain info about the values and the binding to the controls)
    if ( property_model == null ) {
      console.log("Create new property model for resource:"+root_object_uri+" property:"+property);
      property_model = {
        '__metamodel' : {
          property_value_containers : [],
          num_value_controls : 1
        },
        'values' : [
        ]
      }
      root_object[property] = property_model;
    }
    else {
      console.log("Model for resource "+root_object_uri+" already contains info for property "+property);
    }

    var new_ul = $(document.createElement('ul'));
    var new_td = $(document.createElement('td'));

    // Add a property to the control so it knows where the binding info in the metamodel is
    // new_ul.setAttribute('data-metamodel',property_model);
    // new_ul.get(0).setAttribute('data-metamodel','test');

    // Add this control (parent container) to the list of controls for this property
    property_model.__metamodel.property_value_containers.push(new_ul);

    new_td.append(new_ul);

    // Append a row to the table for every property. Each row will support muiltiple values if cardinality says so
    new_table.append($('<tr>').append("<td style=\"vertical-align: top\"><label for=\""+base_property_path+"["+i+"]\">"+propdef.label+"</label></td>",new_td));

    // Work out the root of the property name (The path to an array of values)
    var base_property_path = parent_context+propdef.property_uri

    // For each property, see if there is a value in the model, if so, output an appropriate control
    // For(blah...)

    // Finally, output an empty control to act as a "Next" value (If permitted by cardinality rules)
    // keydown to capture deletes etc keypress for only sensible keys
    var cc = new_ul.append("<li><input id=\""+property+"["+i+"]\" data-resource-uri=\""+root_object_uri+"\" data-property=\""+property+"\" data-property-idx=\""+i+"\" onkeyup=\"scalarUpdated(this);\" type=\"text\"/>[0]</li>")

    var input_control = cc.find('input');
    input_control.get(0).setAttribute("data-metamodel",property_model);

    // parent_element.append("</ul></td></tr>");
  }

  parent_element.append("</table>");

  // var data = $('<div id="'+tab_id+'"></div>').append(tab_content);
  // this.tabs.append(data).tabs('add', '#' + tab_id, tab_name);
  // this.tabs.tabs('select', '#' + tab_id);


}

function scalarUpdated(control) {

  // alert("updateModel "+control.dataset["data-property-path"]);
  var resource_uri = control.getAttribute("data-resource-uri");
  var data_property_path = control.getAttribute("data-property");
  var resource = the_model.__graphmap[resource_uri];
  var metamodel = resource[data_property_path];
  var control_index = parseInt(control.getAttribute('data-property-idx'));

  console.log("scalarUpdated res:"+resource_uri+" prop:"+data_property_path+" idx:"+control_index);
  console.log("old value: "+metamodel.values[control_index]+" new value: "+control.value);

  console.log("metamodel for selected prop %o",metamodel);

  // alert("path:"+data_property_path+" metamodel:"+metamodel+" idx:"+control_index+" count:"+metamodel.__metamodel.property_value_containers.length+" value:"+control.value);

  if ( control_index >= metamodel.values.length ) {
    // We are setting a value on a property which has not been set before. Need to create a new entry in the values array
    var new_value_info = {
      value:"",
      __metamodel:{
        status:"new"
      }
    };
    metamodel.values.push(new_value_info);
  }

  var value_info = metamodel.values[control_index];

  value_info.value = control.value;

  console.log("scalarupdate - control index "+control_index+", len %d",metamodel.__metamodel.num_value_controls);

  // Have we typed in to the last control in the list? If so, append a new blank control for the user to use when adding another value.. IF cardinality > 1
  if ( control_index+1 == metamodel.__metamodel.num_value_controls ) {
    console.log("Add new control....")
    addScalarControl(resource_uri, metamodel, data_property_path);
  }
  else {
    console.log(""+control_index+"+1 != "+metamodel.__metamodel.num_value_controls+" do not add "+(control_index+1));
  }

}

function addScalarControl(resource_uri, metamodel, property) {

  var i = metamodel.__metamodel.num_value_controls++;

  // For each panel where a control appears for this property...
  for ( idx in metamodel.__metamodel.property_value_containers ) {
    // Get hold of the container element for each occurence of this property on a layout
    var c = metamodel.__metamodel.property_value_containers[idx];
    c.append("<li><input id=\""+property+"["+i+"]\"  data-resource-uri=\""+resource_uri+"\" data-property=\""+property+"\" data-property-idx=\""+i+"\" onkeyup=\"scalarUpdated(this);\" type=\"text\"/>["+i+"]</li>")
  }
}
